language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.0.0
  - rbx-2
env:
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.0.0"

gemfile:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile

sudo: false

bundler_args: '--without local_development yard --jobs 3 --retry 3'

script: bundle exec rake

matrix:
  fast_finish: true
  allow_failures:
      - gemfile: gemfiles/activerecord_edge.gemfile
      - rvm: rbx-2
